// <auto-generated />
using System;
using Fluid.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fluid.Entities.Migrations
{
    [DbContext(typeof(FluidDbContext))]
    partial class FluidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fluid.Entities.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_audit_logs_changed_by");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("ProcessedOrders")
                        .HasColumnType("integer")
                        .HasColumnName("processed_orders");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("integer")
                        .HasColumnName("total_orders");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_batches");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_batches_client_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_batches_created_by");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_clients_created_by");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.ClientSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer")
                        .HasColumnName("schema_id");

                    b.HasKey("Id")
                        .HasName("pk_client_schemas");

                    b.HasIndex("SchemaId")
                        .HasDatabaseName("ix_client_schemas_schema_id");

                    b.HasIndex("ClientId", "SchemaId")
                        .IsUnique()
                        .HasDatabaseName("ix_client_schemas_client_id_schema_id");

                    b.ToTable("client_schemas", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blob_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Pages")
                        .HasColumnType("integer")
                        .HasColumnName("pages");

                    b.Property<string>("SearchableBlobName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("searchable_blob_name");

                    b.Property<string>("SearchableText")
                        .HasColumnType("text")
                        .HasColumnName("searchable_text");

                    b.Property<string>("SearchableUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("searchable_url");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_documents_order_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("InputField")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("input_field");

                    b.Property<int>("SchemaFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("schema_field_id");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer")
                        .HasColumnName("schema_id");

                    b.Property<string>("Transformation")
                        .HasColumnType("text")
                        .HasColumnName("transformation");

                    b.HasKey("Id")
                        .HasName("pk_field_mappings");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_field_mappings_client_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_field_mappings_created_by");

                    b.HasIndex("SchemaFieldId")
                        .HasDatabaseName("ix_field_mappings_schema_field_id");

                    b.HasIndex("SchemaId")
                        .HasDatabaseName("ix_field_mappings_schema_id");

                    b.ToTable("field_mappings", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_orders_assigned_to");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_orders_batch_id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.OrderData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("confidence_score");

                    b.Property<string>("Coordinates")
                        .HasColumnType("jsonb")
                        .HasColumnName("coordinates");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("MetaDataValue")
                        .HasColumnType("text")
                        .HasColumnName("meta_data_value");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("ProcessedValue")
                        .HasColumnType("text")
                        .HasColumnName("processed_value");

                    b.Property<int>("SchemaFieldId")
                        .HasColumnType("integer")
                        .HasColumnName("schema_field_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("verified_by");

                    b.HasKey("Id")
                        .HasName("pk_order_data");

                    b.HasIndex("SchemaFieldId")
                        .HasDatabaseName("ix_order_data_schema_field_id");

                    b.HasIndex("VerifiedBy")
                        .HasDatabaseName("ix_order_data_verified_by");

                    b.HasIndex("OrderId", "SchemaFieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_order_data_order_id_schema_field_id");

                    b.ToTable("order_data", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsForServicePrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_service_principal");

                    b.Property<bool?>("IsForTenant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_tenant");

                    b.Property<bool>("IsForUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_user");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsForServicePrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_service_principal");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_roles_created_by_id");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_roles_modified_by_id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Schema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_schemas");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_schemas_created_by");

                    b.ToTable("schemas", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.SchemaField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field_label");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("Format")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("format");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("SchemaId")
                        .HasColumnType("integer")
                        .HasColumnName("schema_id");

                    b.HasKey("Id")
                        .HasName("pk_schema_fields");

                    b.HasIndex("SchemaId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_schema_fields_schema_id_display_order");

                    b.HasIndex("SchemaId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("ix_schema_fields_schema_id_field_name");

                    b.ToTable("schema_fields", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAdId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("azure_ad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AzureAdId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_azure_ad_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("UniqueId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unique_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_roles_created_by_id");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_user_roles_modified_by_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Fluid.Entities.Entities.AuditLog", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.User", "User")
                        .WithMany("ChangedAuditLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_changed_by");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Batch", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Client", "Client")
                        .WithMany("Batches")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_clients_client_id");

                    b.HasOne("Fluid.Entities.Entities.User", "CreatedByUser")
                        .WithMany("CreatedBatches")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_batches_users_created_by");

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Client", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.User", "CreatedByUser")
                        .WithMany("CreatedClients")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_created_by");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.ClientSchema", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Client", "Client")
                        .WithMany("ClientSchemas")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_schemas_clients_client_id");

                    b.HasOne("Fluid.Entities.Entities.Schema", "Schema")
                        .WithMany("ClientSchemas")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_schemas_schemas_schema_id");

                    b.Navigation("Client");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Document", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Order", "Order")
                        .WithMany("Documents")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.FieldMapping", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Client", "Client")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_field_mappings_clients_client_id");

                    b.HasOne("Fluid.Entities.Entities.User", "CreatedByUser")
                        .WithMany("CreatedFieldMappings")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_mappings_users_created_by");

                    b.HasOne("Fluid.Entities.Entities.SchemaField", "SchemaField")
                        .WithMany("FieldMappings")
                        .HasForeignKey("SchemaFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_mappings_schema_fields_schema_field_id");

                    b.HasOne("Fluid.Entities.Entities.Schema", "Schema")
                        .WithMany("FieldMappings")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_field_mappings_schemas_schema_id");

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Schema");

                    b.Navigation("SchemaField");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Order", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.User", "AssignedUser")
                        .WithMany("AssignedWorkItems")
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_users_assigned_to");

                    b.HasOne("Fluid.Entities.Entities.Batch", "Batch")
                        .WithMany("WorkItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_batches_batch_id");

                    b.HasOne("Fluid.Entities.Entities.Client", "Client")
                        .WithMany("WorkItems")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_clients_client_id");

                    b.Navigation("AssignedUser");

                    b.Navigation("Batch");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.OrderData", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Order", "Order")
                        .WithMany("OrderData")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_data_orders_order_id");

                    b.HasOne("Fluid.Entities.Entities.SchemaField", "SchemaField")
                        .WithMany("WorkItemData")
                        .HasForeignKey("SchemaFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_data_schema_fields_schema_field_id");

                    b.HasOne("Fluid.Entities.Entities.User", "VerifiedByUser")
                        .WithMany("VerifiedWorkItemData")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_order_data_users_verified_by");

                    b.Navigation("Order");

                    b.Navigation("SchemaField");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Role", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.User", "CreatedBy")
                        .WithMany("RoleCreatedBies")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roles_users_created_by_id");

                    b.HasOne("Fluid.Entities.Entities.User", "ModifiedBy")
                        .WithMany("RoleModifiedBies")
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roles_users_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.RolePermission", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Fluid.Entities.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Schema", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.User", "CreatedByUser")
                        .WithMany("CreatedSchemas")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schemas_users_created_by");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.SchemaField", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.Schema", "Schema")
                        .WithMany("SchemaFields")
                        .HasForeignKey("SchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schema_fields_schemas_schema_id");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.UserRole", b =>
                {
                    b.HasOne("Fluid.Entities.Entities.User", "CreatedBy")
                        .WithMany("UserRoleCreatedBies")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_users_created_by_id");

                    b.HasOne("Fluid.Entities.Entities.User", "ModifiedBy")
                        .WithMany("UserRoleModifiedBies")
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_users_modified_by_id");

                    b.HasOne("Fluid.Entities.Entities.Role", "Role")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Fluid.Entities.Entities.User", "User")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Batch", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Client", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("ClientSchemas");

                    b.Navigation("FieldMappings");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Order", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("OrderData");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoleUsers");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.Schema", b =>
                {
                    b.Navigation("ClientSchemas");

                    b.Navigation("FieldMappings");

                    b.Navigation("SchemaFields");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.SchemaField", b =>
                {
                    b.Navigation("FieldMappings");

                    b.Navigation("WorkItemData");
                });

            modelBuilder.Entity("Fluid.Entities.Entities.User", b =>
                {
                    b.Navigation("AssignedWorkItems");

                    b.Navigation("ChangedAuditLogs");

                    b.Navigation("CreatedBatches");

                    b.Navigation("CreatedClients");

                    b.Navigation("CreatedFieldMappings");

                    b.Navigation("CreatedSchemas");

                    b.Navigation("RoleCreatedBies");

                    b.Navigation("RoleModifiedBies");

                    b.Navigation("UserRoleCreatedBies");

                    b.Navigation("UserRoleModifiedBies");

                    b.Navigation("UserRoleUsers");

                    b.Navigation("VerifiedWorkItemData");
                });
#pragma warning restore 612, 618
        }
    }
}
